### ISSUE TITLE
Scalability and Performance

### ISSUE THREAD

**Issue by BlaineKTMO** [WSU-4110/Veggie-Garden#10]
|NFR2.  Scalability and Performance |
|---|
|	**Goal**: The program will be able to store and simulate many multiple gardens, and an extensive variety of plants. |
| 	**Description:** The application should be able to store, maintain, and simulate upwards of tens of gardens and upwards of hundreds of plant varieties. This will be accomplished by using lightweight data files and less intensive algorithms for a static, discrete-event simulation.   |
| 	**Origin:** Based on initial project specifications doc. |
| 	**Version:** 1.0  |  
|	**Date:** 09/19/2022 |
|  	**Priority:** 2 |

**Comment by nickynault** [comment]
Runs well on emulator and phone.
