### ISSUE TITLE
Share Content

### ISSUE THREAD

**Issue by gv7491** [WSU-4110/Veggie-Garden#12]
|FR7.|                         
|---|
|**Goal**: FR7 provides the ability to share content with other users.|
| **Description:** The app will allow users to see other individuals’ gardens and their planting tendencies as well as other habits that could possibly assist them in their own gardens. As well as implementation to allow multiple users to track one given garden.|
| **Origin:** Idea was mentioned in conversation on 9/13/2022.|
| **Version:** 1.0  |
|**Date:** 09/18/2022
|  **Priority:** 4 |

**Comment by nickynault** [comment]
Ditched this idea.
