### ISSUE TITLE
Weather Information

### ISSUE THREAD

**Issue by gv7491** [WSU-4110/Veggie-Garden#13]
|FR8 |                         
|---|
|**Goal:** FR8 Provides Weather information for the app|
| **Description:** The app will Allows users to access weather information from their given location of their garden. This will factor into notifications based upon their location from conditions of rain, snow, dry spells, heat, etc.|
| **Origin:** Idea was mentioned in conversation on 9/13/2022|
| **Version:** 1.0  |
|**Date:** 09/18/2022
|  **Priority:** 1.0 |

**Comment by nickynault** [comment]
Completed by TylerW and Blaine
