### ISSUE TITLE
Access Multiple Gardens and Layouts

### ISSUE THREAD

**Issue by gv7491** [WSU-4110/Veggie-Garden#14]
|FR9. |                        
|---|
|**Goal:** FR9 provides the ability for user to access multiple unique gardens. |
| **Description:** The app will Allows users to have access to multiple gardens to track if they wish, possibly differing in location, size, etc. Ideally weather information would be provided for the multiple garden layouts.|
| **Origin:** Idea was mentioned in conversation on 09/15/2022|
| **Version:** 1.0  |
|**Date:** 09/18/2022
|  **Priority:** 4 |

**Comment by nickynault** [comment]
Unfinished
