### ISSUE TITLE
Unique Notification System

### ISSUE THREAD

**Issue by gv7491** [WSU-4110/Veggie-Garden#15]
|FR10. |                           
|---|
|**Goal:** FR10 Provides distinguished notifications for different actions to the user.|
| **Description:** The app will allow users to distinguish whether a given action needs to be performed in their garden or the garden of another person, as well as ideally indicators to distinguish a certain action that needs to be performed.|
| **Origin:** Idea was mentioned in conversation on 09/14/2022. |
| **Version:** 1.0  |
|**Date:** 09/19/2022
|  **Priority:** 2 |

**Comment by nickynault** [comment]
Done by John
