### ISSUE TITLE
Dependability

### ISSUE THREAD

**Issue by gv7491** [WSU-4110/Veggie-Garden#18]
|NFR3. |   
|---|
|**Goal:** NFR3 will make the information given by the app as accurate as possible.|
| **Description:** The app will use the data inputted by the user to ensure accurate predictions on how their plants will develop.|
| **Origin:** Brainstormed Idea on 09/19/2022|
| **Version:** 1.0  |
|**Date:** 09/19/2022
|  **Priority:** 3 |

**Comment by nickynault** [comment]
Database and entry added.
