### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by gv7491** [WSU-4110/Veggie-Garden#19]
|NFR4. |  
|---|
|**Goal:** NFR4 will make the app accessible to users.|
| **Description:** The app will make sure that there won’t be any gestures. Also, options like a colorblind mode and the increase of text size will be implemented.|
| **Origin:** Brainstormed on 09/19/2022|
| **Version:** 1.0  |
|**Date:** 09/19/2022
|  **Priority:** 4 |

**Comment by nickynault** [comment]
App is accessible at the moment.
