### ISSUE TITLE
Plant History

### ISSUE THREAD

**Issue by gv7491** [WSU-4110/Veggie-Garden#21]
|FR15. |    
|---|
|**Goal:** FR15 allows users to see the histories of each plant. |
| **Description:** The app will let users see the history of each of their plants such as how tall they have grown at each date they were checked on, when they flowered, when they were harvested, etc.|
| **Origin:** Very first mention of creating an ap, this became apparent. |
| **Version:** 1.0  |
|**Date:** 09/19/2022
|  **Priority:** 5 |

**Comment by nickynault** [comment]
Scrapped
