### ISSUE TITLE
Automatic Task Scheduling

### ISSUE THREAD

**Issue by BlaineKTMO** [WSU-4110/Veggie-Garden#8]
|FR13.  Automatic Task Scheduling |
|---|
|	**Goal**: The program will utilize information from the user's gardens and plants to automatically create scheduled tasks like watering, fertilizing, harvesting, etc. |
| 	**Description:** When a plant is added to a garden, the application will analyze the plant information, then publish periodic tasks to the calendar like watering. If necessary, it will also add dates for potting, resowing, and fertilizing. |
| 	**Origin:** Based on initial project specifications doc. |
| 	**Version:** 1.0  |  
|	**Date:** 09/19/2022 |
|  	**Priority:** 2 |

**Comment by nickynault** [comment]
Done
