### ISSUE TITLE
Calendar View

### ISSUE THREAD

**Issue by BlaineKTMO** [WSU-4110/Veggie-Garden#9]
|FR14.  Calendar View |
|---|
|	**Goal**: The program will create a visually appealing monthly schedule. |
| 	**Description:** The application will utilize published information from gardens, plants, weather, etc to construct a monthly calendar showing completed and upcoming tasks including watering, repotting, rain, etc. |
| 	**Origin:** Based on initial project specifications doc. |
| 	**Version:** 1.0  |  
|	**Date:** 09/19/2022 |
|  	**Priority:** 1 |

**Comment by nickynault** [comment]
Technically done but not usable.
